### PR TITLE
add vcr design to vcr details section of book

### LINKED ISSUE #30: Section on design of the package, sorta like drake's design chapter
https://books.ropensci.org/drake/design.html

think it's warranted since both webmockr and vcr are quite complex

### PR DESCRIPTION
**Pull request by sckott**
pull in new vcr design vignette fragment in vcr details section of the book

## Related Issue

fix #30

### CODE REVIEW

**Comment by sckott** [comment]
any ideas @maelle ? https://github.com/ropensci-books/http-testing/pull/96/checks?check_run_id=2505087651#step:10:23

**Comment by sckott** [comment]
@maelle  thanks for the fix 

I indented headings by 1 since the headings in the vcr rmdhunk made it so that it created new sections at the same level as other sections in the book https://609c6ea0cd7e5917193893c1--http-testing-book.netlify.app/vcr-intro.html#design

**Review by maelle — APPROVED** [review]
Thank you!

**Comment by sckott** [comment]
should we merge ?

**Pull request merged**
